name: public_speak_cac_2024
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  change_app_package_name: ^1.3.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^0.8.6
  simple_gradient_text: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/login_screen/
    - assets/icons/

