name: public_speak_cac_2024
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  change_app_package_name: ^1.3.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  simple_gradient_text: ^1.3.0
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets: 
    - assets/icons/home/home_icon.png
    - assets/icons/home/home_selected_icon.png
    - assets/icons/podium/podium_icon.png
    - assets/icons/podium/podium_selected_icon.png
    - assets/icons/briefcase/briefcase_icon.png
    - assets/icons/briefcase/briefcase_selected_icon.png
    - assets/login_temp_background.jpeg
    - assets/login_screen/facebook_icon.png
    - assets/login_screen/apple_icon.png
    - assets/login_screen/google_icon.png
    - assets/speakup_logo.png
  fonts:
  - family: Poppins
    fonts: 
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
  uses-material-design: true